---

# Copyright 2023 Wong Hoi Sing Edison <hswong3i@pantarei-design.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

_zypper_repository:
  - name: "repo-backports-debug-update"
    description: "Update repository with updates for openSUSE Leap debuginfo packages from openSUSE Backports"
    enabled: false
    autorefresh: true
    repo: "http://downloadcontent.opensuse.org/update/leap/$releasever/backports_debug/"
    state: "present"
  - name: "repo-backports-update"
    description: "Update repository of openSUSE Backports"
    enabled: true
    autorefresh: true
    repo: "http://downloadcontent.opensuse.org/update/leap/$releasever/backports/"
    state: "present"
  - name: "repo-debug-non-oss"
    description: "Debug Repository (Non-OSS)"
    enabled: false
    autorefresh: true
    repo: "http://downloadcontent.opensuse.org/debug/distribution/leap/$releasever/repo/non-oss/"
    state: "present"
  - name: "repo-debug-update-non-oss"
    description: "Update Repository (Debug, Non-OSS)"
    enabled: false
    autorefresh: true
    repo: "http://downloadcontent.opensuse.org/debug/update/leap/$releasever/non-oss/"
    state: "present"
  - name: "repo-debug-update"
    description: "Update Repository (Debug)"
    enabled: false
    autorefresh: true
    repo: "http://downloadcontent.opensuse.org/debug/update/leap/$releasever/oss/"
    state: "present"
  - name: "repo-debug"
    description: "Debug Repository"
    enabled: false
    autorefresh: true
    repo: "http://downloadcontent.opensuse.org/debug/distribution/leap/$releasever/repo/oss/"
    state: "present"
  - name: "repo-non-oss"
    description: "Non-OSS Repository"
    enabled: true
    autorefresh: true
    repo: "http://downloadcontent.opensuse.org/distribution/leap/$releasever/repo/non-oss/"
    state: "present"
  - name: "repo-oss"
    description: "Main Repository"
    enabled: true
    autorefresh: true
    repo: "http://downloadcontent.opensuse.org/distribution/leap/$releasever/repo/oss/"
    state: "present"
  - name: "repo-sle-debug-update"
    description: "Update repository with debuginfo for updates from SUSE Linux Enterprise 15"
    enabled: false
    autorefresh: true
    repo: "http://downloadcontent.opensuse.org/debug/update/leap/$releasever/sle/"
    state: "present"
  - name: "repo-sle-update"
    description: "Update repository with updates from SUSE Linux Enterprise 15"
    enabled: true
    autorefresh: true
    repo: "http://downloadcontent.opensuse.org/update/leap/$releasever/sle/"
    state: "present"
  - name: "repo-source"
    description: "Source Repository"
    enabled: false
    autorefresh: true
    repo: "http://downloadcontent.opensuse.org/source/distribution/leap/$releasever/repo/oss/"
    state: "present"
  - name: "repo-update-non-oss"
    description: "Update Repository (Non-Oss)"
    enabled: true
    autorefresh: true
    repo: "http://downloadcontent.opensuse.org/update/leap/$releasever/non-oss/"
    state: "present"
  - name: "repo-update"
    description: "Main Update Repository"
    enabled: true
    autorefresh: true
    repo: "http://downloadcontent.opensuse.org/update/leap/$releasever/oss/"
    state: "present"

_zypper:
  - { state: "latest", name: "ca-certificates" }
  - { state: "latest", name: "cloud-init" }
  - { state: "latest", name: "curl" }
  - { state: "latest", name: "gcc" }
  - { state: "latest", name: "growpart" }
  - { state: "latest", name: "insserv-compat" }
  - { state: "latest", name: "iproute2" }
  - { state: "latest", name: "kernel-default" }
  - { state: "latest", name: "kernel-source" }
  - { state: "latest", name: "libXmu6" }
  - { state: "latest", name: "libXt6" }
  - { state: "latest", name: "make" }
  - { state: "latest", name: "openssh" }
  - { state: "latest", name: "perl" }
  - { state: "latest", name: "python3" }
  - { state: "latest", name: "rsync" }
  - { state: "latest", name: "shadow" }
  - { state: "latest", name: "sudo" }
  - { state: "latest", name: "util-linux" }
