---
# Copyright 2024 Wong Hoi Sing Edison <hswong3i@pantarei-design.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: copy templates
  ansible.builtin.template:
    dest: "{{ item.dest }}"
    src: "{{ item.src | default('./templates' + item.dest + '.j2') }}"
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
    mode: "{{ item.mode | default('0644') }}"
  loop:
    - { dest: /etc/apt/preferences.d/99-backports.pref }
    - { dest: /etc/apt/preferences.d/nosnap.pref }
    - { dest: /etc/apt/sources.list }

- name: prepare files
  ansible.builtin.file:
    dest: "{{ item.dest }}"
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
    mode: "{{ item.mode | default('0644') }}"
    state: "{{ item.state | default('file') }}"
  loop:
    - { dest: /etc/apt/sources.list.d/debian.sources, state: absent }
    - { dest: /etc/apt/sources.list.d/ubuntu.sources, state: absent }

- name: apt-get update
  ansible.builtin.apt:
    update_cache: true
  changed_when: false

- name: apt-get dist-upgrade
  ansible.builtin.apt:
    upgrade: dist
  register: result
  until: result is succeeded

- name: apt-get install
  ansible.builtin.apt:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  loop: "{{ _apt }}"
  register: result
  until: result is succeeded

- name: update /etc/default/grub
  community.general.ini_file:
    path: /etc/default/grub
    section: ""
    option: "{{ item.option }}"
    value: '"{{ item.value }}"'
    mode: "0644"
    no_extra_spaces: true
    state: present
  loop:
    - { option: GRUB_DEFAULT, value: "0" }
    - { option: GRUB_CMDLINE_LINUX, value: net.ifnames=0 biosdevname=0 systemd.unified_cgroup_hierarchy=0 }
    - { option: GRUB_CMDLINE_LINUX_DEFAULT, value: net.ifnames=0 biosdevname=0 systemd.unified_cgroup_hierarchy=0 }

- name: update-grub
  ansible.builtin.command:
    cmd: update-grub
  changed_when: false
  failed_when: false

- name: update-initramfs -c -k all
  ansible.builtin.command:
    cmd: update-initramfs -c -k all
  changed_when: false
  failed_when: false
