---

# (c) Wong Hoi Sing Edison <hswong3i@pantarei-design.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: zypper addrepo
  vars:
    ansible_python_interpreter: "python3"
  community.general.zypper_repository:
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    enabled: "{{ item.enabled }}"
    autorefresh: "{{ item.autorefresh }}"
    repo: "{{ item.repo }}"
    state: "{{ item.state }}"
    overwrite_multiple: true
  loop: "{{ _zypper_repository }}"
  register: result
  until: result is succeeded

- name: zypper update
  vars:
    ansible_python_interpreter: "python3"
  community.general.zypper:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  loop:
    - { name: "*", state: "latest" }
  register: result
  until: result is succeeded

- name: zypper install
  vars:
    ansible_python_interpreter: "python3"
  community.general.zypper:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  loop: "{{ _zypper }}"
  register: result
  until: result is succeeded

- name: update /etc/default/grub
  community.general.ini_file:
    path: "/etc/default/grub"
    section: ""
    option: "{{ item.option }}"
    value: "\"{{ item.value }}\""
    mode: "0644"
    no_extra_spaces: true
    state: "present"
  loop:
    - { option: "GRUB_DEFAULT", value: "0" }
    - { option: "GRUB_CMDLINE_LINUX", value: "net.ifnames=0 biosdevname=0 systemd.unified_cgroup_hierarchy=0" }
    - { option: "GRUB_CMDLINE_LINUX_DEFAULT", value: "net.ifnames=0 biosdevname=0 systemd.unified_cgroup_hierarchy=0" }

- name: grub2-mkconfig -o /boot/grub2/grub.cfg
  ansible.builtin.command: grub2-mkconfig -o /boot/grub2/grub.cfg
  changed_when: false
  failed_when: false

- name: dracut -f
  ansible.builtin.command: dracut -f
  changed_when: false
  failed_when: false

- name: zypper install qemu-guest-agent
  community.general.zypper:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  loop:
    - { state: "latest", name: "qemu-guest-agent" }
  when:
    - ansible_virtualization_type | lower == 'kvm'
  register: result
  until: result is succeeded

- name: sh VBoxLinuxAdditions.run
  ansible.builtin.shell: |
    set -euxo pipefail
    VERSION=$(curl -skL -m 300 http://download.virtualbox.org/virtualbox/LATEST.TXT)
    cd /tmp
    curl -skL -m 300 -O http://download.virtualbox.org/virtualbox/$VERSION/VBoxGuestAdditions_$VERSION.iso
    TMP_DIR="$(mktemp -d)"
    mount -o loop /tmp/VBoxGuestAdditions_$VERSION.iso $TMP_DIR
    (echo "y" | sh $TMP_DIR/VBoxLinuxAdditions.run) || echo $?
    umount $TMP_DIR
    rm -rf $TMP_DIR /tmp/VBoxGuestAdditions_$VERSION.iso
  args:
    executable: "/bin/bash"
  when:
    - ansible_virtualization_type | lower == 'virtualbox'
  register: result
  until: result is succeeded
  changed_when: result is not succeeded
